// DO NOT EDIT. generated by webtyp.com/ormc

package roomlayout

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Floor struct {
	Id string
	TenantId string
	Name string
	Position int64
	UpdatedAt int64
}

func (m *Floor) ModelName() string { return "floor" }

func (m *Floor) Schema() []model.Field { return FloorModel.Fields }

func (m *Floor) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Name, &m.Position, &m.UpdatedAt} }

func (m *Floor) IsNil() bool { return m == nil }

func (m *Floor) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("name", m.Name)
	if m.Position != 0 { w.Int("position", m.Position) }
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Floor) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Int("position"); ok { m.Position = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type FloorList []*Floor

func (s *FloorList) Len() int             { return len(*s) }
func (s *FloorList) At(i int) model.Fielder { return (*s)[i] }
func (s *FloorList) Append() model.Fielder  { v := &Floor{}; *s = append(*s, v); return v }
func (s *FloorList) IsNil() bool          { return s == nil }
func (s *FloorList) EncodeFields(_ model.FieldWriter) {}
func (s *FloorList) DecodeFields(_ model.FieldReader) {}

func (m *Floor) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Floor_ = struct {
	Id string
	TenantId string
	Name string
	Position string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Name: "name",
	Position: "position",
	UpdatedAt: "updated_at",
}

func ReadOneFloor(qb *orm.QB, model *Floor) (*Floor, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllFloor(qb *orm.QB) (FloorList, error) {
	var results FloorList
	err := qb.ReadAll(
		func() model.Model { return &Floor{} },
		func(m model.Model) { results = append(results, m.(*Floor)) },
	)
	return results, err
}

type Room struct {
	Id string
	TenantId string
	FloorId string
	Code string
	Name string
	Notes string
	IsActive bool
	UpdatedAt int64
}

func (m *Room) ModelName() string { return "room" }

func (m *Room) Schema() []model.Field { return RoomModel.Fields }

func (m *Room) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.FloorId, &m.Code, &m.Name, &m.Notes, &m.IsActive, &m.UpdatedAt} }

func (m *Room) IsNil() bool { return m == nil }

func (m *Room) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("floor_id", m.FloorId)
	w.String("code", m.Code)
	w.String("name", m.Name)
	if m.Notes != "" { w.String("notes", m.Notes) }
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Room) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("floor_id"); ok { m.FloorId = v }
	if v, ok := r.String("code"); ok { m.Code = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("notes"); ok { m.Notes = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type RoomList []*Room

func (s *RoomList) Len() int             { return len(*s) }
func (s *RoomList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoomList) Append() model.Fielder  { v := &Room{}; *s = append(*s, v); return v }
func (s *RoomList) IsNil() bool          { return s == nil }
func (s *RoomList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomList) DecodeFields(_ model.FieldReader) {}

func (m *Room) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Room_ = struct {
	Id string
	TenantId string
	FloorId string
	Code string
	Name string
	Notes string
	IsActive string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	FloorId: "floor_id",
	Code: "code",
	Name: "name",
	Notes: "notes",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneRoom(qb *orm.QB, model *Room) (*Room, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRoom(qb *orm.QB) (RoomList, error) {
	var results RoomList
	err := qb.ReadAll(
		func() model.Model { return &Room{} },
		func(m model.Model) { results = append(results, m.(*Room)) },
	)
	return results, err
}

func (m *Room) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: RoomModel.Fields[2], Ref: "floor", RefColumn: "id", OnDelete: ""},
	}
}

type Equipment struct {
	Id string
	TenantId string
	Name string
	UpdatedAt int64
}

func (m *Equipment) ModelName() string { return "equipment" }

func (m *Equipment) Schema() []model.Field { return EquipmentModel.Fields }

func (m *Equipment) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Name, &m.UpdatedAt} }

func (m *Equipment) IsNil() bool { return m == nil }

func (m *Equipment) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("name", m.Name)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Equipment) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type EquipmentList []*Equipment

func (s *EquipmentList) Len() int             { return len(*s) }
func (s *EquipmentList) At(i int) model.Fielder { return (*s)[i] }
func (s *EquipmentList) Append() model.Fielder  { v := &Equipment{}; *s = append(*s, v); return v }
func (s *EquipmentList) IsNil() bool          { return s == nil }
func (s *EquipmentList) EncodeFields(_ model.FieldWriter) {}
func (s *EquipmentList) DecodeFields(_ model.FieldReader) {}

func (m *Equipment) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Equipment_ = struct {
	Id string
	TenantId string
	Name string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Name: "name",
	UpdatedAt: "updated_at",
}

func ReadOneEquipment(qb *orm.QB, model *Equipment) (*Equipment, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllEquipment(qb *orm.QB) (EquipmentList, error) {
	var results EquipmentList
	err := qb.ReadAll(
		func() model.Model { return &Equipment{} },
		func(m model.Model) { results = append(results, m.(*Equipment)) },
	)
	return results, err
}

type RoomEquipment struct {
	TenantId string
	RoomId string
	EquipmentId string
}

func (m *RoomEquipment) ModelName() string { return "room_equipment" }

func (m *RoomEquipment) Schema() []model.Field { return RoomEquipmentModel.Fields }

func (m *RoomEquipment) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.EquipmentId} }

func (m *RoomEquipment) IsNil() bool { return m == nil }

func (m *RoomEquipment) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("equipment_id", m.EquipmentId)
}

func (m *RoomEquipment) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("equipment_id"); ok { m.EquipmentId = v }
}

type RoomEquipmentList []*RoomEquipment

func (s *RoomEquipmentList) Len() int             { return len(*s) }
func (s *RoomEquipmentList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoomEquipmentList) Append() model.Fielder  { v := &RoomEquipment{}; *s = append(*s, v); return v }
func (s *RoomEquipmentList) IsNil() bool          { return s == nil }
func (s *RoomEquipmentList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomEquipmentList) DecodeFields(_ model.FieldReader) {}

func (m *RoomEquipment) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var RoomEquipment_ = struct {
	TenantId string
	RoomId string
	EquipmentId string
}{
	TenantId: "tenant_id",
	RoomId: "room_id",
	EquipmentId: "equipment_id",
}

func ReadOneRoomEquipment(qb *orm.QB, model *RoomEquipment) (*RoomEquipment, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRoomEquipment(qb *orm.QB) (RoomEquipmentList, error) {
	var results RoomEquipmentList
	err := qb.ReadAll(
		func() model.Model { return &RoomEquipment{} },
		func(m model.Model) { results = append(results, m.(*RoomEquipment)) },
	)
	return results, err
}

func (m *RoomEquipment) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: RoomEquipmentModel.Fields[1], Ref: "room", RefColumn: "id", OnDelete: ""},
		{Field: RoomEquipmentModel.Fields[2], Ref: "equipment", RefColumn: "id", OnDelete: ""},
	}
}

type RoomCategory struct {
	TenantId string
	RoomId string
	CategoryId string
}

func (m *RoomCategory) ModelName() string { return "room_category" }

func (m *RoomCategory) Schema() []model.Field { return RoomCategoryModel.Fields }

func (m *RoomCategory) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.CategoryId} }

func (m *RoomCategory) IsNil() bool { return m == nil }

func (m *RoomCategory) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("category_id", m.CategoryId)
}

func (m *RoomCategory) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
}

type RoomCategoryList []*RoomCategory

func (s *RoomCategoryList) Len() int             { return len(*s) }
func (s *RoomCategoryList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoomCategoryList) Append() model.Fielder  { v := &RoomCategory{}; *s = append(*s, v); return v }
func (s *RoomCategoryList) IsNil() bool          { return s == nil }
func (s *RoomCategoryList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomCategoryList) DecodeFields(_ model.FieldReader) {}

func (m *RoomCategory) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var RoomCategory_ = struct {
	TenantId string
	RoomId string
	CategoryId string
}{
	TenantId: "tenant_id",
	RoomId: "room_id",
	CategoryId: "category_id",
}

func ReadOneRoomCategory(qb *orm.QB, model *RoomCategory) (*RoomCategory, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRoomCategory(qb *orm.QB) (RoomCategoryList, error) {
	var results RoomCategoryList
	err := qb.ReadAll(
		func() model.Model { return &RoomCategory{} },
		func(m model.Model) { results = append(results, m.(*RoomCategory)) },
	)
	return results, err
}

func (m *RoomCategory) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: RoomCategoryModel.Fields[1], Ref: "room", RefColumn: "id", OnDelete: ""},
	}
}

type RoomShift struct {
	Id string
	TenantId string
	RoomId string
	CategoryId string
	OccupantId string
	OccupantLabel string
	DayOfWeek int64
	SpecificDate int64
	StartMin int64
	EndMin int64
	IsActive bool
	UpdatedAt int64
}

func (m *RoomShift) ModelName() string { return "room_shift" }

func (m *RoomShift) Schema() []model.Field { return RoomShiftModel.Fields }

func (m *RoomShift) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.RoomId, &m.CategoryId, &m.OccupantId, &m.OccupantLabel, &m.DayOfWeek, &m.SpecificDate, &m.StartMin, &m.EndMin, &m.IsActive, &m.UpdatedAt} }

func (m *RoomShift) IsNil() bool { return m == nil }

func (m *RoomShift) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("category_id", m.CategoryId)
	if m.OccupantId != "" { w.String("occupant_id", m.OccupantId) }
	w.String("occupant_label", m.OccupantLabel)
	w.Int("day_of_week", m.DayOfWeek)
	w.Int("specific_date", m.SpecificDate)
	w.Int("start_min", m.StartMin)
	w.Int("end_min", m.EndMin)
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *RoomShift) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
	if v, ok := r.String("occupant_id"); ok { m.OccupantId = v }
	if v, ok := r.String("occupant_label"); ok { m.OccupantLabel = v }
	if v, ok := r.Int("day_of_week"); ok { m.DayOfWeek = v }
	if v, ok := r.Int("specific_date"); ok { m.SpecificDate = v }
	if v, ok := r.Int("start_min"); ok { m.StartMin = v }
	if v, ok := r.Int("end_min"); ok { m.EndMin = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type RoomShiftList []*RoomShift

func (s *RoomShiftList) Len() int             { return len(*s) }
func (s *RoomShiftList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoomShiftList) Append() model.Fielder  { v := &RoomShift{}; *s = append(*s, v); return v }
func (s *RoomShiftList) IsNil() bool          { return s == nil }
func (s *RoomShiftList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomShiftList) DecodeFields(_ model.FieldReader) {}

func (m *RoomShift) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var RoomShift_ = struct {
	Id string
	TenantId string
	RoomId string
	CategoryId string
	OccupantId string
	OccupantLabel string
	DayOfWeek string
	SpecificDate string
	StartMin string
	EndMin string
	IsActive string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	RoomId: "room_id",
	CategoryId: "category_id",
	OccupantId: "occupant_id",
	OccupantLabel: "occupant_label",
	DayOfWeek: "day_of_week",
	SpecificDate: "specific_date",
	StartMin: "start_min",
	EndMin: "end_min",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneRoomShift(qb *orm.QB, model *RoomShift) (*RoomShift, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRoomShift(qb *orm.QB) (RoomShiftList, error) {
	var results RoomShiftList
	err := qb.ReadAll(
		func() model.Model { return &RoomShift{} },
		func(m model.Model) { results = append(results, m.(*RoomShift)) },
	)
	return results, err
}

func (m *RoomShift) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: RoomShiftModel.Fields[2], Ref: "room", RefColumn: "id", OnDelete: ""},
	}
}

type RoomShiftCancellation struct {
	TenantId string
	ShiftId string
	SpecificDate int64
}

func (m *RoomShiftCancellation) ModelName() string { return "room_shift_cancellation" }

func (m *RoomShiftCancellation) Schema() []model.Field { return RoomShiftCancellationModel.Fields }

func (m *RoomShiftCancellation) Pointers() []any { return []any{&m.TenantId, &m.ShiftId, &m.SpecificDate} }

func (m *RoomShiftCancellation) IsNil() bool { return m == nil }

func (m *RoomShiftCancellation) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("shift_id", m.ShiftId)
	w.Int("specific_date", m.SpecificDate)
}

func (m *RoomShiftCancellation) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("shift_id"); ok { m.ShiftId = v }
	if v, ok := r.Int("specific_date"); ok { m.SpecificDate = v }
}

type RoomShiftCancellationList []*RoomShiftCancellation

func (s *RoomShiftCancellationList) Len() int             { return len(*s) }
func (s *RoomShiftCancellationList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoomShiftCancellationList) Append() model.Fielder  { v := &RoomShiftCancellation{}; *s = append(*s, v); return v }
func (s *RoomShiftCancellationList) IsNil() bool          { return s == nil }
func (s *RoomShiftCancellationList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomShiftCancellationList) DecodeFields(_ model.FieldReader) {}

func (m *RoomShiftCancellation) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var RoomShiftCancellation_ = struct {
	TenantId string
	ShiftId string
	SpecificDate string
}{
	TenantId: "tenant_id",
	ShiftId: "shift_id",
	SpecificDate: "specific_date",
}

func ReadOneRoomShiftCancellation(qb *orm.QB, model *RoomShiftCancellation) (*RoomShiftCancellation, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRoomShiftCancellation(qb *orm.QB) (RoomShiftCancellationList, error) {
	var results RoomShiftCancellationList
	err := qb.ReadAll(
		func() model.Model { return &RoomShiftCancellation{} },
		func(m model.Model) { results = append(results, m.(*RoomShiftCancellation)) },
	)
	return results, err
}

func (m *RoomShiftCancellation) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: RoomShiftCancellationModel.Fields[1], Ref: "room_shift", RefColumn: "id", OnDelete: ""},
	}
}

type RoomShiftForm struct {
	Id string
	RoomId string
	CategoryId string
	OccupantId string
	OccupantLabel string
	DayOfWeek string
	Date string
	Start string
	End string
}

func (m *RoomShiftForm) ModelName() string { return "room_shift_form" }

func (m *RoomShiftForm) Schema() []model.Field { return RoomShiftFormModel.Fields }

func (m *RoomShiftForm) Pointers() []any { return []any{&m.Id, &m.RoomId, &m.CategoryId, &m.OccupantId, &m.OccupantLabel, &m.DayOfWeek, &m.Date, &m.Start, &m.End} }

func (m *RoomShiftForm) IsNil() bool { return m == nil }

func (m *RoomShiftForm) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("room_id", m.RoomId)
	w.String("category_id", m.CategoryId)
	if m.OccupantId != "" { w.String("occupant_id", m.OccupantId) }
	if m.OccupantLabel != "" { w.String("occupant_label", m.OccupantLabel) }
	if m.DayOfWeek != "" { w.String("day_of_week", m.DayOfWeek) }
	if m.Date != "" { w.String("date", m.Date) }
	w.String("start", m.Start)
	w.String("end", m.End)
}

func (m *RoomShiftForm) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
	if v, ok := r.String("occupant_id"); ok { m.OccupantId = v }
	if v, ok := r.String("occupant_label"); ok { m.OccupantLabel = v }
	if v, ok := r.String("day_of_week"); ok { m.DayOfWeek = v }
	if v, ok := r.String("date"); ok { m.Date = v }
	if v, ok := r.String("start"); ok { m.Start = v }
	if v, ok := r.String("end"); ok { m.End = v }
}

type RoomShiftFormList []*RoomShiftForm

func (s *RoomShiftFormList) Len() int             { return len(*s) }
func (s *RoomShiftFormList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoomShiftFormList) Append() model.Fielder  { v := &RoomShiftForm{}; *s = append(*s, v); return v }
func (s *RoomShiftFormList) IsNil() bool          { return s == nil }
func (s *RoomShiftFormList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomShiftFormList) DecodeFields(_ model.FieldReader) {}

func (m *RoomShiftForm) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type IdRef struct {
	Id string
}

func (m *IdRef) ModelName() string { return "id_ref" }

func (m *IdRef) Schema() []model.Field { return IdRefModel.Fields }

func (m *IdRef) Pointers() []any { return []any{&m.Id} }

func (m *IdRef) IsNil() bool { return m == nil }

func (m *IdRef) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
}

func (m *IdRef) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
}

type IdRefList []*IdRef

func (s *IdRefList) Len() int             { return len(*s) }
func (s *IdRefList) At(i int) model.Fielder { return (*s)[i] }
func (s *IdRefList) Append() model.Fielder  { v := &IdRef{}; *s = append(*s, v); return v }
func (s *IdRefList) IsNil() bool          { return s == nil }
func (s *IdRefList) EncodeFields(_ model.FieldWriter) {}
func (s *IdRefList) DecodeFields(_ model.FieldReader) {}

func (m *IdRef) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListFloorsArgs struct {
	TenantId string
}

func (m *ListFloorsArgs) ModelName() string { return "list_floors_args" }

func (m *ListFloorsArgs) Schema() []model.Field { return ListFloorsArgsModel.Fields }

func (m *ListFloorsArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *ListFloorsArgs) IsNil() bool { return m == nil }

func (m *ListFloorsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *ListFloorsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
}

type ListFloorsArgsList []*ListFloorsArgs

func (s *ListFloorsArgsList) Len() int             { return len(*s) }
func (s *ListFloorsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListFloorsArgsList) Append() model.Fielder  { v := &ListFloorsArgs{}; *s = append(*s, v); return v }
func (s *ListFloorsArgsList) IsNil() bool          { return s == nil }
func (s *ListFloorsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListFloorsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListFloorsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteFloorArgs struct {
	TenantId string
	Id string
}

func (m *DeleteFloorArgs) ModelName() string { return "delete_floor_args" }

func (m *DeleteFloorArgs) Schema() []model.Field { return DeleteFloorArgsModel.Fields }

func (m *DeleteFloorArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteFloorArgs) IsNil() bool { return m == nil }

func (m *DeleteFloorArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteFloorArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteFloorArgsList []*DeleteFloorArgs

func (s *DeleteFloorArgsList) Len() int             { return len(*s) }
func (s *DeleteFloorArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteFloorArgsList) Append() model.Fielder  { v := &DeleteFloorArgs{}; *s = append(*s, v); return v }
func (s *DeleteFloorArgsList) IsNil() bool          { return s == nil }
func (s *DeleteFloorArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteFloorArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteFloorArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListRoomsArgs struct {
	TenantId string
	ActiveOnly bool
}

func (m *ListRoomsArgs) ModelName() string { return "list_rooms_args" }

func (m *ListRoomsArgs) Schema() []model.Field { return ListRoomsArgsModel.Fields }

func (m *ListRoomsArgs) Pointers() []any { return []any{&m.TenantId, &m.ActiveOnly} }

func (m *ListRoomsArgs) IsNil() bool { return m == nil }

func (m *ListRoomsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.Bool("active_only", m.ActiveOnly)
}

func (m *ListRoomsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.Bool("active_only"); ok { m.ActiveOnly = v }
}

type ListRoomsArgsList []*ListRoomsArgs

func (s *ListRoomsArgsList) Len() int             { return len(*s) }
func (s *ListRoomsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListRoomsArgsList) Append() model.Fielder  { v := &ListRoomsArgs{}; *s = append(*s, v); return v }
func (s *ListRoomsArgsList) IsNil() bool          { return s == nil }
func (s *ListRoomsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListRoomsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListRoomsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetRoomArgs struct {
	TenantId string
	Id string
}

func (m *GetRoomArgs) ModelName() string { return "get_room_args" }

func (m *GetRoomArgs) Schema() []model.Field { return GetRoomArgsModel.Fields }

func (m *GetRoomArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *GetRoomArgs) IsNil() bool { return m == nil }

func (m *GetRoomArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetRoomArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetRoomArgsList []*GetRoomArgs

func (s *GetRoomArgsList) Len() int             { return len(*s) }
func (s *GetRoomArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetRoomArgsList) Append() model.Fielder  { v := &GetRoomArgs{}; *s = append(*s, v); return v }
func (s *GetRoomArgsList) IsNil() bool          { return s == nil }
func (s *GetRoomArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetRoomArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetRoomArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeactivateRoomArgs struct {
	TenantId string
	Id string
}

func (m *DeactivateRoomArgs) ModelName() string { return "deactivate_room_args" }

func (m *DeactivateRoomArgs) Schema() []model.Field { return DeactivateRoomArgsModel.Fields }

func (m *DeactivateRoomArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeactivateRoomArgs) IsNil() bool { return m == nil }

func (m *DeactivateRoomArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeactivateRoomArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeactivateRoomArgsList []*DeactivateRoomArgs

func (s *DeactivateRoomArgsList) Len() int             { return len(*s) }
func (s *DeactivateRoomArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeactivateRoomArgsList) Append() model.Fielder  { v := &DeactivateRoomArgs{}; *s = append(*s, v); return v }
func (s *DeactivateRoomArgsList) IsNil() bool          { return s == nil }
func (s *DeactivateRoomArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeactivateRoomArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeactivateRoomArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListEquipmentArgs struct {
	TenantId string
}

func (m *ListEquipmentArgs) ModelName() string { return "list_equipment_args" }

func (m *ListEquipmentArgs) Schema() []model.Field { return ListEquipmentArgsModel.Fields }

func (m *ListEquipmentArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *ListEquipmentArgs) IsNil() bool { return m == nil }

func (m *ListEquipmentArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *ListEquipmentArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
}

type ListEquipmentArgsList []*ListEquipmentArgs

func (s *ListEquipmentArgsList) Len() int             { return len(*s) }
func (s *ListEquipmentArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListEquipmentArgsList) Append() model.Fielder  { v := &ListEquipmentArgs{}; *s = append(*s, v); return v }
func (s *ListEquipmentArgsList) IsNil() bool          { return s == nil }
func (s *ListEquipmentArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListEquipmentArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListEquipmentArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteEquipmentArgs struct {
	TenantId string
	Id string
}

func (m *DeleteEquipmentArgs) ModelName() string { return "delete_equipment_args" }

func (m *DeleteEquipmentArgs) Schema() []model.Field { return DeleteEquipmentArgsModel.Fields }

func (m *DeleteEquipmentArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteEquipmentArgs) IsNil() bool { return m == nil }

func (m *DeleteEquipmentArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteEquipmentArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteEquipmentArgsList []*DeleteEquipmentArgs

func (s *DeleteEquipmentArgsList) Len() int             { return len(*s) }
func (s *DeleteEquipmentArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteEquipmentArgsList) Append() model.Fielder  { v := &DeleteEquipmentArgs{}; *s = append(*s, v); return v }
func (s *DeleteEquipmentArgsList) IsNil() bool          { return s == nil }
func (s *DeleteEquipmentArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteEquipmentArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteEquipmentArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListRoomEquipmentArgs struct {
	TenantId string
	RoomId string
}

func (m *ListRoomEquipmentArgs) ModelName() string { return "list_room_equipment_args" }

func (m *ListRoomEquipmentArgs) Schema() []model.Field { return ListRoomEquipmentArgsModel.Fields }

func (m *ListRoomEquipmentArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId} }

func (m *ListRoomEquipmentArgs) IsNil() bool { return m == nil }

func (m *ListRoomEquipmentArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
}

func (m *ListRoomEquipmentArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
}

type ListRoomEquipmentArgsList []*ListRoomEquipmentArgs

func (s *ListRoomEquipmentArgsList) Len() int             { return len(*s) }
func (s *ListRoomEquipmentArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListRoomEquipmentArgsList) Append() model.Fielder  { v := &ListRoomEquipmentArgs{}; *s = append(*s, v); return v }
func (s *ListRoomEquipmentArgsList) IsNil() bool          { return s == nil }
func (s *ListRoomEquipmentArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListRoomEquipmentArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListRoomEquipmentArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SetRoomEquipmentArgs struct {
	TenantId string
	RoomId string
	EquipmentIds []IdRef
}

func (m *SetRoomEquipmentArgs) ModelName() string { return "set_room_equipment_args" }

func (m *SetRoomEquipmentArgs) Schema() []model.Field { return SetRoomEquipmentArgsModel.Fields }

func (m *SetRoomEquipmentArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.EquipmentIds} }

func (m *SetRoomEquipmentArgs) IsNil() bool { return m == nil }

func (m *SetRoomEquipmentArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
		{
			arr := w.Array("equipment_ids", len(m.EquipmentIds))
			for _, x := range m.EquipmentIds {
				arr.Object(&x)
			}
			arr.Close()
		}
}

func (m *SetRoomEquipmentArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if arr, ok := r.Array("equipment_ids"); ok {
		n := arr.Len()
		m.EquipmentIds = make([]IdRef, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.EquipmentIds[i])
		}
	}
}

type SetRoomEquipmentArgsList []*SetRoomEquipmentArgs

func (s *SetRoomEquipmentArgsList) Len() int             { return len(*s) }
func (s *SetRoomEquipmentArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SetRoomEquipmentArgsList) Append() model.Fielder  { v := &SetRoomEquipmentArgs{}; *s = append(*s, v); return v }
func (s *SetRoomEquipmentArgsList) IsNil() bool          { return s == nil }
func (s *SetRoomEquipmentArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SetRoomEquipmentArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SetRoomEquipmentArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListRoomCategoriesArgs struct {
	TenantId string
	RoomId string
}

func (m *ListRoomCategoriesArgs) ModelName() string { return "list_room_categories_args" }

func (m *ListRoomCategoriesArgs) Schema() []model.Field { return ListRoomCategoriesArgsModel.Fields }

func (m *ListRoomCategoriesArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId} }

func (m *ListRoomCategoriesArgs) IsNil() bool { return m == nil }

func (m *ListRoomCategoriesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
}

func (m *ListRoomCategoriesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
}

type ListRoomCategoriesArgsList []*ListRoomCategoriesArgs

func (s *ListRoomCategoriesArgsList) Len() int             { return len(*s) }
func (s *ListRoomCategoriesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListRoomCategoriesArgsList) Append() model.Fielder  { v := &ListRoomCategoriesArgs{}; *s = append(*s, v); return v }
func (s *ListRoomCategoriesArgsList) IsNil() bool          { return s == nil }
func (s *ListRoomCategoriesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListRoomCategoriesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListRoomCategoriesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SetRoomCategoriesArgs struct {
	TenantId string
	RoomId string
	CategoryIds []IdRef
}

func (m *SetRoomCategoriesArgs) ModelName() string { return "set_room_categories_args" }

func (m *SetRoomCategoriesArgs) Schema() []model.Field { return SetRoomCategoriesArgsModel.Fields }

func (m *SetRoomCategoriesArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.CategoryIds} }

func (m *SetRoomCategoriesArgs) IsNil() bool { return m == nil }

func (m *SetRoomCategoriesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
		{
			arr := w.Array("category_ids", len(m.CategoryIds))
			for _, x := range m.CategoryIds {
				arr.Object(&x)
			}
			arr.Close()
		}
}

func (m *SetRoomCategoriesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if arr, ok := r.Array("category_ids"); ok {
		n := arr.Len()
		m.CategoryIds = make([]IdRef, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.CategoryIds[i])
		}
	}
}

type SetRoomCategoriesArgsList []*SetRoomCategoriesArgs

func (s *SetRoomCategoriesArgsList) Len() int             { return len(*s) }
func (s *SetRoomCategoriesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SetRoomCategoriesArgsList) Append() model.Fielder  { v := &SetRoomCategoriesArgs{}; *s = append(*s, v); return v }
func (s *SetRoomCategoriesArgsList) IsNil() bool          { return s == nil }
func (s *SetRoomCategoriesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SetRoomCategoriesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SetRoomCategoriesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListOptionsArgs struct {
	TenantId string
}

func (m *ListOptionsArgs) ModelName() string { return "list_options_args" }

func (m *ListOptionsArgs) Schema() []model.Field { return ListOptionsArgsModel.Fields }

func (m *ListOptionsArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *ListOptionsArgs) IsNil() bool { return m == nil }

func (m *ListOptionsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *ListOptionsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
}

type ListOptionsArgsList []*ListOptionsArgs

func (s *ListOptionsArgsList) Len() int             { return len(*s) }
func (s *ListOptionsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListOptionsArgsList) Append() model.Fielder  { v := &ListOptionsArgs{}; *s = append(*s, v); return v }
func (s *ListOptionsArgsList) IsNil() bool          { return s == nil }
func (s *ListOptionsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListOptionsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListOptionsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListRoomShiftsArgs struct {
	TenantId string
	RoomId string
}

func (m *ListRoomShiftsArgs) ModelName() string { return "list_room_shifts_args" }

func (m *ListRoomShiftsArgs) Schema() []model.Field { return ListRoomShiftsArgsModel.Fields }

func (m *ListRoomShiftsArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId} }

func (m *ListRoomShiftsArgs) IsNil() bool { return m == nil }

func (m *ListRoomShiftsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
}

func (m *ListRoomShiftsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
}

type ListRoomShiftsArgsList []*ListRoomShiftsArgs

func (s *ListRoomShiftsArgsList) Len() int             { return len(*s) }
func (s *ListRoomShiftsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListRoomShiftsArgsList) Append() model.Fielder  { v := &ListRoomShiftsArgs{}; *s = append(*s, v); return v }
func (s *ListRoomShiftsArgsList) IsNil() bool          { return s == nil }
func (s *ListRoomShiftsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListRoomShiftsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListRoomShiftsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteRoomShiftArgs struct {
	TenantId string
	Id string
}

func (m *DeleteRoomShiftArgs) ModelName() string { return "delete_room_shift_args" }

func (m *DeleteRoomShiftArgs) Schema() []model.Field { return DeleteRoomShiftArgsModel.Fields }

func (m *DeleteRoomShiftArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteRoomShiftArgs) IsNil() bool { return m == nil }

func (m *DeleteRoomShiftArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteRoomShiftArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteRoomShiftArgsList []*DeleteRoomShiftArgs

func (s *DeleteRoomShiftArgsList) Len() int             { return len(*s) }
func (s *DeleteRoomShiftArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteRoomShiftArgsList) Append() model.Fielder  { v := &DeleteRoomShiftArgs{}; *s = append(*s, v); return v }
func (s *DeleteRoomShiftArgsList) IsNil() bool          { return s == nil }
func (s *DeleteRoomShiftArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteRoomShiftArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteRoomShiftArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type CancelShiftOccurrenceArgs struct {
	TenantId string
	ShiftId string
	Date string
}

func (m *CancelShiftOccurrenceArgs) ModelName() string { return "cancel_shift_occurrence_args" }

func (m *CancelShiftOccurrenceArgs) Schema() []model.Field { return CancelShiftOccurrenceArgsModel.Fields }

func (m *CancelShiftOccurrenceArgs) Pointers() []any { return []any{&m.TenantId, &m.ShiftId, &m.Date} }

func (m *CancelShiftOccurrenceArgs) IsNil() bool { return m == nil }

func (m *CancelShiftOccurrenceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("shift_id", m.ShiftId)
	w.String("date", m.Date)
}

func (m *CancelShiftOccurrenceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("shift_id"); ok { m.ShiftId = v }
	if v, ok := r.String("date"); ok { m.Date = v }
}

type CancelShiftOccurrenceArgsList []*CancelShiftOccurrenceArgs

func (s *CancelShiftOccurrenceArgsList) Len() int             { return len(*s) }
func (s *CancelShiftOccurrenceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *CancelShiftOccurrenceArgsList) Append() model.Fielder  { v := &CancelShiftOccurrenceArgs{}; *s = append(*s, v); return v }
func (s *CancelShiftOccurrenceArgsList) IsNil() bool          { return s == nil }
func (s *CancelShiftOccurrenceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *CancelShiftOccurrenceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *CancelShiftOccurrenceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type MoveShiftOccurrenceArgs struct {
	TenantId string
	ShiftId string
	Date string
	TargetRoomId string
}

func (m *MoveShiftOccurrenceArgs) ModelName() string { return "move_shift_occurrence_args" }

func (m *MoveShiftOccurrenceArgs) Schema() []model.Field { return MoveShiftOccurrenceArgsModel.Fields }

func (m *MoveShiftOccurrenceArgs) Pointers() []any { return []any{&m.TenantId, &m.ShiftId, &m.Date, &m.TargetRoomId} }

func (m *MoveShiftOccurrenceArgs) IsNil() bool { return m == nil }

func (m *MoveShiftOccurrenceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("shift_id", m.ShiftId)
	w.String("date", m.Date)
	w.String("target_room_id", m.TargetRoomId)
}

func (m *MoveShiftOccurrenceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("shift_id"); ok { m.ShiftId = v }
	if v, ok := r.String("date"); ok { m.Date = v }
	if v, ok := r.String("target_room_id"); ok { m.TargetRoomId = v }
}

type MoveShiftOccurrenceArgsList []*MoveShiftOccurrenceArgs

func (s *MoveShiftOccurrenceArgsList) Len() int             { return len(*s) }
func (s *MoveShiftOccurrenceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *MoveShiftOccurrenceArgsList) Append() model.Fielder  { v := &MoveShiftOccurrenceArgs{}; *s = append(*s, v); return v }
func (s *MoveShiftOccurrenceArgsList) IsNil() bool          { return s == nil }
func (s *MoveShiftOccurrenceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *MoveShiftOccurrenceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *MoveShiftOccurrenceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListRoomDayArgs struct {
	TenantId string
	RoomId string
	Date string
}

func (m *ListRoomDayArgs) ModelName() string { return "list_room_day_args" }

func (m *ListRoomDayArgs) Schema() []model.Field { return ListRoomDayArgsModel.Fields }

func (m *ListRoomDayArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.Date} }

func (m *ListRoomDayArgs) IsNil() bool { return m == nil }

func (m *ListRoomDayArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("date", m.Date)
}

func (m *ListRoomDayArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("date"); ok { m.Date = v }
}

type ListRoomDayArgsList []*ListRoomDayArgs

func (s *ListRoomDayArgsList) Len() int             { return len(*s) }
func (s *ListRoomDayArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListRoomDayArgsList) Append() model.Fielder  { v := &ListRoomDayArgs{}; *s = append(*s, v); return v }
func (s *ListRoomDayArgsList) IsNil() bool          { return s == nil }
func (s *ListRoomDayArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListRoomDayArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListRoomDayArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListBoardArgs struct {
	TenantId string
	CategoryId string
	EquipmentId string
}

func (m *ListBoardArgs) ModelName() string { return "list_board_args" }

func (m *ListBoardArgs) Schema() []model.Field { return ListBoardArgsModel.Fields }

func (m *ListBoardArgs) Pointers() []any { return []any{&m.TenantId, &m.CategoryId, &m.EquipmentId} }

func (m *ListBoardArgs) IsNil() bool { return m == nil }

func (m *ListBoardArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("category_id", m.CategoryId)
	w.String("equipment_id", m.EquipmentId)
}

func (m *ListBoardArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
	if v, ok := r.String("equipment_id"); ok { m.EquipmentId = v }
}

type ListBoardArgsList []*ListBoardArgs

func (s *ListBoardArgsList) Len() int             { return len(*s) }
func (s *ListBoardArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListBoardArgsList) Append() model.Fielder  { v := &ListBoardArgs{}; *s = append(*s, v); return v }
func (s *ListBoardArgsList) IsNil() bool          { return s == nil }
func (s *ListBoardArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListBoardArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListBoardArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type FindFreeRoomsArgs struct {
	TenantId string
	Date string
	Start string
	End string
	CategoryId string
}

func (m *FindFreeRoomsArgs) ModelName() string { return "find_free_rooms_args" }

func (m *FindFreeRoomsArgs) Schema() []model.Field { return FindFreeRoomsArgsModel.Fields }

func (m *FindFreeRoomsArgs) Pointers() []any { return []any{&m.TenantId, &m.Date, &m.Start, &m.End, &m.CategoryId} }

func (m *FindFreeRoomsArgs) IsNil() bool { return m == nil }

func (m *FindFreeRoomsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("date", m.Date)
	w.String("start", m.Start)
	w.String("end", m.End)
	w.String("category_id", m.CategoryId)
}

func (m *FindFreeRoomsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("date"); ok { m.Date = v }
	if v, ok := r.String("start"); ok { m.Start = v }
	if v, ok := r.String("end"); ok { m.End = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
}

type FindFreeRoomsArgsList []*FindFreeRoomsArgs

func (s *FindFreeRoomsArgsList) Len() int             { return len(*s) }
func (s *FindFreeRoomsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *FindFreeRoomsArgsList) Append() model.Fielder  { v := &FindFreeRoomsArgs{}; *s = append(*s, v); return v }
func (s *FindFreeRoomsArgsList) IsNil() bool          { return s == nil }
func (s *FindFreeRoomsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *FindFreeRoomsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *FindFreeRoomsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListPublicAvailabilityArgs struct {
	Date string
	CategoryId string
}

func (m *ListPublicAvailabilityArgs) ModelName() string { return "list_public_availability_args" }

func (m *ListPublicAvailabilityArgs) Schema() []model.Field { return ListPublicAvailabilityArgsModel.Fields }

func (m *ListPublicAvailabilityArgs) Pointers() []any { return []any{&m.Date, &m.CategoryId} }

func (m *ListPublicAvailabilityArgs) IsNil() bool { return m == nil }

func (m *ListPublicAvailabilityArgs) EncodeFields(w model.FieldWriter) {
	w.String("date", m.Date)
	w.String("category_id", m.CategoryId)
}

func (m *ListPublicAvailabilityArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("date"); ok { m.Date = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
}

type ListPublicAvailabilityArgsList []*ListPublicAvailabilityArgs

func (s *ListPublicAvailabilityArgsList) Len() int             { return len(*s) }
func (s *ListPublicAvailabilityArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListPublicAvailabilityArgsList) Append() model.Fielder  { v := &ListPublicAvailabilityArgs{}; *s = append(*s, v); return v }
func (s *ListPublicAvailabilityArgsList) IsNil() bool          { return s == nil }
func (s *ListPublicAvailabilityArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListPublicAvailabilityArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListPublicAvailabilityArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Option struct {
	Id string
	Label string
}

func (m *Option) ModelName() string { return "option" }

func (m *Option) Schema() []model.Field { return OptionModel.Fields }

func (m *Option) Pointers() []any { return []any{&m.Id, &m.Label} }

func (m *Option) IsNil() bool { return m == nil }

func (m *Option) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("label", m.Label)
}

func (m *Option) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("label"); ok { m.Label = v }
}

type OptionList []*Option

func (s *OptionList) Len() int             { return len(*s) }
func (s *OptionList) At(i int) model.Fielder { return (*s)[i] }
func (s *OptionList) Append() model.Fielder  { v := &Option{}; *s = append(*s, v); return v }
func (s *OptionList) IsNil() bool          { return s == nil }
func (s *OptionList) EncodeFields(_ model.FieldWriter) {}
func (s *OptionList) DecodeFields(_ model.FieldReader) {}

func (m *Option) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DayShift struct {
	ShiftId string
	RoomId string
	RoomCode string
	CategoryId string
	CategoryLabel string
	OccupantId string
	OccupantLabel string
	Start string
	End string
	IsWeekly bool
}

func (m *DayShift) ModelName() string { return "day_shift" }

func (m *DayShift) Schema() []model.Field { return DayShiftModel.Fields }

func (m *DayShift) Pointers() []any { return []any{&m.ShiftId, &m.RoomId, &m.RoomCode, &m.CategoryId, &m.CategoryLabel, &m.OccupantId, &m.OccupantLabel, &m.Start, &m.End, &m.IsWeekly} }

func (m *DayShift) IsNil() bool { return m == nil }

func (m *DayShift) EncodeFields(w model.FieldWriter) {
	w.String("shift_id", m.ShiftId)
	w.String("room_id", m.RoomId)
	w.String("room_code", m.RoomCode)
	w.String("category_id", m.CategoryId)
	w.String("category_label", m.CategoryLabel)
	w.String("occupant_id", m.OccupantId)
	w.String("occupant_label", m.OccupantLabel)
	w.String("start", m.Start)
	w.String("end", m.End)
	w.Bool("is_weekly", m.IsWeekly)
}

func (m *DayShift) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("shift_id"); ok { m.ShiftId = v }
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("room_code"); ok { m.RoomCode = v }
	if v, ok := r.String("category_id"); ok { m.CategoryId = v }
	if v, ok := r.String("category_label"); ok { m.CategoryLabel = v }
	if v, ok := r.String("occupant_id"); ok { m.OccupantId = v }
	if v, ok := r.String("occupant_label"); ok { m.OccupantLabel = v }
	if v, ok := r.String("start"); ok { m.Start = v }
	if v, ok := r.String("end"); ok { m.End = v }
	if v, ok := r.Bool("is_weekly"); ok { m.IsWeekly = v }
}

type DayShiftList []*DayShift

func (s *DayShiftList) Len() int             { return len(*s) }
func (s *DayShiftList) At(i int) model.Fielder { return (*s)[i] }
func (s *DayShiftList) Append() model.Fielder  { v := &DayShift{}; *s = append(*s, v); return v }
func (s *DayShiftList) IsNil() bool          { return s == nil }
func (s *DayShiftList) EncodeFields(_ model.FieldWriter) {}
func (s *DayShiftList) DecodeFields(_ model.FieldReader) {}

func (m *DayShift) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type BoardRoom struct {
	RoomId string
	Code string
	Name string
	FloorName string
	FloorPosition int64
	CategoryLabels string
	EquipmentLabels string
	Status string
	CurrentOccupantLabel string
	CurrentUntil string
	NextStart string
	NextOccupantLabel string
	Today string
}

func (m *BoardRoom) ModelName() string { return "board_room" }

func (m *BoardRoom) Schema() []model.Field { return BoardRoomModel.Fields }

func (m *BoardRoom) Pointers() []any { return []any{&m.RoomId, &m.Code, &m.Name, &m.FloorName, &m.FloorPosition, &m.CategoryLabels, &m.EquipmentLabels, &m.Status, &m.CurrentOccupantLabel, &m.CurrentUntil, &m.NextStart, &m.NextOccupantLabel, &m.Today} }

func (m *BoardRoom) IsNil() bool { return m == nil }

func (m *BoardRoom) EncodeFields(w model.FieldWriter) {
	w.String("room_id", m.RoomId)
	w.String("code", m.Code)
	w.String("name", m.Name)
	w.String("floor_name", m.FloorName)
	w.Int("floor_position", m.FloorPosition)
	w.String("category_labels", m.CategoryLabels)
	w.String("equipment_labels", m.EquipmentLabels)
	w.String("status", m.Status)
	w.String("current_occupant_label", m.CurrentOccupantLabel)
	w.String("current_until", m.CurrentUntil)
	w.String("next_start", m.NextStart)
	w.String("next_occupant_label", m.NextOccupantLabel)
	w.String("today", m.Today)
}

func (m *BoardRoom) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("code"); ok { m.Code = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("floor_name"); ok { m.FloorName = v }
	if v, ok := r.Int("floor_position"); ok { m.FloorPosition = v }
	if v, ok := r.String("category_labels"); ok { m.CategoryLabels = v }
	if v, ok := r.String("equipment_labels"); ok { m.EquipmentLabels = v }
	if v, ok := r.String("status"); ok { m.Status = v }
	if v, ok := r.String("current_occupant_label"); ok { m.CurrentOccupantLabel = v }
	if v, ok := r.String("current_until"); ok { m.CurrentUntil = v }
	if v, ok := r.String("next_start"); ok { m.NextStart = v }
	if v, ok := r.String("next_occupant_label"); ok { m.NextOccupantLabel = v }
	if v, ok := r.String("today"); ok { m.Today = v }
}

type BoardRoomList []*BoardRoom

func (s *BoardRoomList) Len() int             { return len(*s) }
func (s *BoardRoomList) At(i int) model.Fielder { return (*s)[i] }
func (s *BoardRoomList) Append() model.Fielder  { v := &BoardRoom{}; *s = append(*s, v); return v }
func (s *BoardRoomList) IsNil() bool          { return s == nil }
func (s *BoardRoomList) EncodeFields(_ model.FieldWriter) {}
func (s *BoardRoomList) DecodeFields(_ model.FieldReader) {}

func (m *BoardRoom) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type FreeRoom struct {
	RoomId string
	Code string
	Name string
	FloorName string
	EquipmentLabels string
}

func (m *FreeRoom) ModelName() string { return "free_room" }

func (m *FreeRoom) Schema() []model.Field { return FreeRoomModel.Fields }

func (m *FreeRoom) Pointers() []any { return []any{&m.RoomId, &m.Code, &m.Name, &m.FloorName, &m.EquipmentLabels} }

func (m *FreeRoom) IsNil() bool { return m == nil }

func (m *FreeRoom) EncodeFields(w model.FieldWriter) {
	w.String("room_id", m.RoomId)
	w.String("code", m.Code)
	w.String("name", m.Name)
	w.String("floor_name", m.FloorName)
	w.String("equipment_labels", m.EquipmentLabels)
}

func (m *FreeRoom) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("room_id"); ok { m.RoomId = v }
	if v, ok := r.String("code"); ok { m.Code = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("floor_name"); ok { m.FloorName = v }
	if v, ok := r.String("equipment_labels"); ok { m.EquipmentLabels = v }
}

type FreeRoomList []*FreeRoom

func (s *FreeRoomList) Len() int             { return len(*s) }
func (s *FreeRoomList) At(i int) model.Fielder { return (*s)[i] }
func (s *FreeRoomList) Append() model.Fielder  { v := &FreeRoom{}; *s = append(*s, v); return v }
func (s *FreeRoomList) IsNil() bool          { return s == nil }
func (s *FreeRoomList) EncodeFields(_ model.FieldWriter) {}
func (s *FreeRoomList) DecodeFields(_ model.FieldReader) {}

func (m *FreeRoom) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type PublicSlot struct {
	RoomCode string
	RoomName string
	FloorName string
	Start string
	End string
}

func (m *PublicSlot) ModelName() string { return "public_slot" }

func (m *PublicSlot) Schema() []model.Field { return PublicSlotModel.Fields }

func (m *PublicSlot) Pointers() []any { return []any{&m.RoomCode, &m.RoomName, &m.FloorName, &m.Start, &m.End} }

func (m *PublicSlot) IsNil() bool { return m == nil }

func (m *PublicSlot) EncodeFields(w model.FieldWriter) {
	w.String("room_code", m.RoomCode)
	w.String("room_name", m.RoomName)
	w.String("floor_name", m.FloorName)
	w.String("start", m.Start)
	w.String("end", m.End)
}

func (m *PublicSlot) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("room_code"); ok { m.RoomCode = v }
	if v, ok := r.String("room_name"); ok { m.RoomName = v }
	if v, ok := r.String("floor_name"); ok { m.FloorName = v }
	if v, ok := r.String("start"); ok { m.Start = v }
	if v, ok := r.String("end"); ok { m.End = v }
}

type PublicSlotList []*PublicSlot

func (s *PublicSlotList) Len() int             { return len(*s) }
func (s *PublicSlotList) At(i int) model.Fielder { return (*s)[i] }
func (s *PublicSlotList) Append() model.Fielder  { v := &PublicSlot{}; *s = append(*s, v); return v }
func (s *PublicSlotList) IsNil() bool          { return s == nil }
func (s *PublicSlotList) EncodeFields(_ model.FieldWriter) {}
func (s *PublicSlotList) DecodeFields(_ model.FieldReader) {}

func (m *PublicSlot) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
